name: GitHub Actions Demo

on: 
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: ["main"]

  schedule:
    - cron: 15 6 * * SUN

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: output event
        run: echo "event name:" ${{ github.event_name }}
      - name: output branch
        run: echo "event name:" ${{ github.ref }}
      - name: output files
        run: echo $(ls ${{ github.workspace }})
